### ISSUE TITLE
Does PvPManager take over the playerKillPlayer event entirely? 

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#497]
### Describe the bug
My CMI playerKillPlayer EventCommands stopped working recently, but all the other event commands work fine, the only thing I can think of is that PvPmanager could also be listning to this server event and somehow taking it over, this has been working for a long time and seems to be a recent issue.

If this is likley, is it possible to work with CMI to make sure that the eventCommands are not broken.

I have just noticed you also have `Player Kills.Commands On Kill` with <player> <victim> and <item> so I could migrate my commands to PvPmanager, BUT the issue I have is that sometimes we get a confict where the commands will run Via CMI and I presume, the other times when they dont run in CMI they are trying to be run in PvPManager, Im not sure if disabeling CMIs playerKillPlayer event lets PvPManager listen entirely or vice versa 

This is my CMI config just incase you wanted to re-produce.
Sends kill titles, resets back and sends a sound, /ho is just a staff message to try and diagnose if it was even firing!

CMI does have quite a few more options/placeholders when it comes to options too, might be worth adding a few so you match!
```yaml
playerKillPlayer:
  # [sourceName] to insert source player name
  # [sourceDisplayName] to insert player display name
  # [sourceLvl] to insert player level
  # [sourceExp] to insert player total exp
  # [sourceHp] to insert player health
  # [sourceMaxHp] to insert player max health
  # [sourceHunger] to insert player hunger level
  # [sourceGameMode] to insert player gamemode
  # Keep in mind that in case you are using specialized commands, then Commands section will be performed on player who died and SourceCommands will be performed on player who killed
  Enabled: true
  Commands:
  - cmi titlemsg [sourceName] &4&l⚔ &4Killed &c[playerName]\n&7%otherplayer_iteminhand_[sourceName]%
    -in:20 -out:20 -keep:80
  - cmi sound chime [sourceName]
  - cmi titlemsg [playerName] &c[sourceName]&7 Killed you!\n%otherplayer_iteminhand_[sourceName]%
    -in:20 -out:20 -keep:100
  - cmi resetback [playerName] -death
  - ho [sourceName] killed [playerName]
  SourceCommands: []
```

### To reproduce the bug

1. Use CMI and in `Settings/modules.yml` enable `eventCommands: true` Reboot the server to enable.
2. In `Settings/EventCommands.yml` set `playerKillPlayer` `Enabled: true` and set some commands
3. Commands do not fire from CMI playerKillPlayer

### Plugin and Server version
[15:28:07] [Server thread/INFO]: PvPManager version 3.32.13
[15:28:07] [Server thread/INFO]: A powerful plugin to manage various PvP combat features
[15:28:07] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/pvpmanager.10610/
[15:28:07] [Server thread/INFO]: Author: ChanceSD

### Additional information
Also posted to CMI to see which plugin is at fault here https://github.com/Zrips/CMI/issues/8737
