### ISSUE TITLE
Re-enable pvpmanager.nopvp, This was used for temp staff ranks.

### ISSUE THREAD

**Issue by TomLewis** [ChanceSD/PvPManager#508]
I have no idea what repo to post in there are two? https://github.com/ChanceSD/PvPManager-Issues/issues/191

**Is your feature request related to a problem? Please describe.**
The purpose I used `pvpmanager.nopvp` was to have ranks not be in PvP, for example I have a "gardener" rank that is temp given to players to clean up the world, I also have a second temp rank called "Media" that takes screenshots, These two ranks need to have PvP disabled for both them attacking and others attacking them when they are busy in staff mode. When the ranks run out (via lp) then this permission auto removes.

Personally I would never need to use the world manager setting for any purpose, but I really need that  `pvpmanager.nopvp`.

Just spent like 30 mins trying to figure out why the hell it wasn't working, then did a verbose and noticed it didn't exist, then had to backtrack changelogs... 

please can we get it back!

Other permissions I also had in these staff ranks were;
```
- pvpmanager.nopvp:
    world: PirateCraft_1
    value: true
- pvpmanager.nopvetag:
    world: PirateCraft_1
    value: true
- pvpmanager.nocombat:
    world: PirateCraft_1
    value: true
```
